# Generated by Django 4.2.2 on 2023-06-28 20:54

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):
    dependencies = [
        ("hobby", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hobby",
            name="days_of_hobby",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    ("monday", "Monday"),
                    ("tuesday", "Tuesday"),
                    ("wednesday", "Wednesday"),
                    ("thursday", "Thursday"),
                    ("friday", "Friday"),
                    ("saturday", "Saturday"),
                    ("sunday", "Sunday"),
                ],
                max_length=56,
            ),
        ),
    ]
