# Generated by Django 4.2.3 on 2023-07-26 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hobby', '0002_alter_hobby_days_of_hobby'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=200, verbose_name='اسم الصنف ')),
                ('size', models.IntegerField(verbose_name='المقاس')),
                ('sell_price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='سعر البيع ')),
                ('buy_price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='سعر الشراء ')),
                ('Quantity', models.IntegerField(verbose_name='الكميه')),
                ('barcode', models.CharField(max_length=50, verbose_name='باركود')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
